### ISSUE TITLE
大佬，这个项目拉下来之后，编译会出错

### ISSUE THREAD

**Issue by somebodyZw** [dosgo/xsocks#2]
![image](https://user-images.githubusercontent.com/42363949/88914992-10fa7c00-d296-11ea-9587-94461dd6fd75.png)
![image](https://user-images.githubusercontent.com/42363949/88914908-f6c09e00-d295-11ea-8825-7ad4af59834a.png),
我的golang版本是 go1.14.6 windows/amd64
请问是哪里出了问题呢？我将项目导入goland，编译错误的地方并没有提示错误，将mod中的内容删除，重新go get -d -v ./... 
结果同样的错误

**Comment by dosgo** [comment]
谷歌库的问题，把这两个方法注释掉就行了。。不影响使用，我们没接入ICMP

**Comment by dosgo** [comment]
应该是谷歌开源的时候没有整理导致的。。

**Comment by dosgo** [comment]
应该是谷歌开源的时候没有整理导致的。。
