### ISSUE TITLE
编译 ARM5版本会产生错误

### ISSUE THREAD

**Issue by jojo147** [dosgo/xsocks#4]
程序 : xsocks  	分支:  master  版本号: 1.4.1-(20210306)-45-g12d7c6f   go1.16.5

之前也编译过但是编译 ARM5版时会出现这样的问题

GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 CGO_LDFLAGS=-static  go build -a -trimpath -ldflags "-w -s "  -o xsocks_server_arm5  ./cli/server.go

# gvisor.dev/gvisor/pkg/tcpip/transport/tcp
../../../../pkg/mod/gvisor.dev/gvisor@v0.0.0-20201215175918-b0f23fb7e0cf/pkg/tcpip/transport/tcp/snd.go:336:16: constant 9223372036854775807 overflows int

编译  AMD64  与  ARM64版本没有问题

就是 ARM5版会出现问题

**Comment by dosgo** [comment]
由于依赖的库gvisor还在开发中，不支持32位，你可以手动修改snd.go的数值最大值，然后重新编译。。

**Comment by jojo147** [comment]
把出问题那行
s.sndSsthresh = math.MaxInt64

改成  
s.sndSsthresh = math.MaxInt32

果然就编译成功了

**Comment by dosgo** [comment]
对，但是官方就是不想修复。。现在连个正式版本都没有
