### ISSUE TITLE
error slow

### ISSUE THREAD

**Issue by MCjorsh5** [dosgo/xsocks#5]
try to make a tunnel with this in the client it works fast 15 seconds, and then it becomes too slow I think it is a problem with the server and not with the android client unless I send wrong code to the client and cause it to do that

**Comment by dosgo** [comment]
Are you using quic mode?

**Comment by MCjorsh5** [comment]
UDP, I wanted to test the socks5 but it does not appear in the client it does not work with the port that the server gives. You have a telegram, I would like us to talk

**Comment by dosgo** [comment]
No telegram, udp? What are your server and client startup parameters?

**Comment by MCjorsh5** [comment]
yes Sudp, I use android client

**Comment by MCjorsh5** [comment]
How can I contact you I want to make a donation $ to the project if you help me with something

**Comment by dosgo** [comment]
sudp mode may have bugs, it is recommended to use quic or websocket.

**Comment by dosgo** [comment]
What you need to do.

**Comment by dosgo** [comment]
There are many problems in sudp mode, which mainly cause server memory overflow, which is not a good mode, so I added the current limit in line 63 of remoteTun.go. This may be caused by this. I still recommend quic, which also uses udp. And mature a lot.

**Comment by MCjorsh5** [comment]
is that I need socks5 traffic which is TCP but also UDP apart to make a tunnel = (how can I contact you to better talk about the subject

**Comment by dosgo** [comment]
The socks5 protocol supports udp. And it is turned on by default, but udp needs to be requested in accordance with the socks5 protocol.

**Comment by MCjorsh5** [comment]
Can we talk in any way? I will make a donation if you help me

**Comment by dosgo** [comment]
Currently it is supported by default, you don’t need to consider this issue, client/tun2socks.go line 105, comm/socks/socks.go line 103 will be processed automatically.

**Comment by dosgo** [comment]
The principle is that a local udp gateway sends an acquisition request to the server through channels such as quic, and the server forwards it to the udp target address, and the data reply from the udp target also returns through the response. It is basically a modified version of the socks5 protocol.

**Comment by MCjorsh5** [comment]
is that I have used quicky websocket and it still does not work in my tunnel so I need more personalized help

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/137091338-4b313bb5-7308-4b11-8af2-de123c768983.png)
![image](https://user-images.githubusercontent.com/9545458/137091605-ff06b927-c265-4ffb-a78f-74d9f4c60278.png)
youtube uses http3, and http3 is the udp used, indicating that there is no problem with the udp tunnel. I think you may have misunderstood the use of this.

**Comment by dosgo** [comment]
What version of xsocks are you using.

**Comment by MCjorsh5** [comment]
the latest version can you upgrade to SDK 30?

**Comment by dosgo** [comment]
No, unless compiled with gomobile.

**Comment by MCjorsh5** [comment]
can't update then api 30?

**Comment by dosgo** [comment]
The latest dev branch support has been changed to aar, and the new Android SDK.
