### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by fuqiang03** [dosgo/xsocks#6]
在openwrt 环境中  go 1.18.2下

github.com/dosgo/xsocks/comm/dot
# github.com/dosgo/xsocks/server
../../server/comm.go:181:17: cannot use pkt.NetworkHeader().View() (value of type *bufferv2.View) as type []byte in argument to buffer.Write
../../server/comm.go:182:17: cannot use pkt.TransportHeader().View() (value of type *bufferv2.View) as type []byte in argument to buffer.Write
../../server/comm.go:183:38: pkt.Data().AsRange().ToOwnedView undefined (type stack.Range has no field or method ToOwnedView)
../../server/sudp.go:101:17: cannot use pkt.NetworkHeader().View() (value of type *bufferv2.View) as type []byte in argument to buffer.Write
../../server/sudp.go:102:17: cannot use pkt.TransportHeader().View() (value of type *bufferv2.View) as type []byte in argument to buffer.Write
../../server/sudp.go:103:38: pkt.Data().AsRange().ToOwnedView undefined (type stack.Range has no field or method ToOwnedView)
github.com/dosgo/xsocks/client/tunnelcomm
github.com/dosgo/xsocks/client

**Comment by dosgo** [comment]
修复了，不过如果你用1.18版本，我还是建议你使用7月23日的版本

**Comment by fuqiang03** [comment]
已经通过,
